version: "3.3"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    ports:
      - "1880:80"
    volumes:
      - "./data/files:/srv"
      - "./data/db:/db"
      - "./config.json:/.filebrowser.json"
    restart: "always"
