version: "3.3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.6.0
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    restart: "always"
