version: '3.3'

services:
  etcd:
    image: "quay.io/coreos/etcd:v3.4.13"
    container_name: "etcdv3"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
    volumes: 
      - ./etcd:/etcd
    ports:
    - 2379:2379
    - 2380:2380
    - 4001:4001