version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3.7.7
    hostname: "rabbitmq"
    environment:
      TZ: "Asia/Shanghai"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQQ"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "B2RDRidpEm"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./data:/var/lib/rabbitmq/mnesia"
    restart: "always"
