version: "3.3"

services:
  portainer:
    image: portainer/portainer:1.19.1
    ports:
      - "19000:9000"
    volumes:
      - "./data:/data"
      - "./password:/tmp/password"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["--admin-password-file=/tmp/password"]
    restart: "always"
