version: "3.3"

services:
  mysql:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=vi9ZqIQB9T
    ports:
      - "13306:3306"
    volumes:
      - "./data:/var/lib/mysql"
      - "./mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    restart: "always"
