version: "3.3"

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: "zookeeper"
    ports:
      - "2181:2181"
    restart: "always"
  kafka:
    image: wurstmeister/kafka:2.11-0.10.2.2
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stream-in:1:1,stream-out:1:1"
    ports:
      - "9092:9092"
    volumes:
      - "./data:/kafka"
    restart: "always"
